server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
          team: DevOps
          env: Prod
          component:
  - job_name: shoehub
    static_configs:
      - targets:
          - localhost
        labels:
          job: shoehub
          app: shoehub
          __path__: /var/log/shoehub/log*
          team: QA
          env: Stage
  - job_name: python_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: python-gen
          app: python-gen
          __path__: /var/log/*.log
          team: Audit
          env: Dev-env
          component:
          level:
    pipeline_stages:
    - logfmt:
        mapping:
          component:
          level:
    - labels:
        component:
        level:
