{
 "title": "ShoeHub",
 "tags": [
  "tech",
  "shoehub"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": {
     "query": "label_values(shoehub_payments{PaymentMethod=\"Card\"} , CountryCode)"
    }
   },
   {
    "name": "paymentMethod",
    "label": "Payment Method",
    "query": {
     "query": "label_values(shoehub_payments{CountryCode=\"US\"} , PaymentMethod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Tech Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ERROR RATE",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "rate({level=\"ERROR\", component=\"database\"} |= `` [1m])"
    },
    {
     "direction": "backward",
     "expr": "rate({component=\"database\", level=\"ERROR\"} |= `` [10m])"
    }
   ]
  },
  {
   "title": "Logs Component Backend",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/var/log/loki.log\", component=\"backend\"} |= ``"
    }
   ]
  },
  {
   "title": "Responne Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(microsoft_aspnetcore_hosting_http_server_request_duration_sum[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs Component Database",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/var/log/loki.log\", component=\"database\"} |= ``",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Summary ERROR",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "rate({component=\"backend\", level=\"ERROR\"} |= `` [1h])"
    },
    {
     "direction": "backward",
     "expr": "rate({component=\"database\", level=\"ERROR\"} |= `` [1h])"
    }
   ]
  },
  { "title": "Business Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Payment Amount by Mehtod of $paymentMethod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "repeat": "paymentMethod",
   "targets": [
    {
     "expr": "shoehub_payments{PaymentMethod=\"$paymentMethod\"}",
     "legendFormat": "{{CountryCode}}"
    }
   ]
  },
  {
   "title": "Sales",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Boots\"}[1m])",
     "legendFormat": "Boots"
    },
    {
     "expr": "rate(shoehub_sales{ShoeType=\"HighHeels\"}[1m])",
     "legendFormat": "HighHeels"
    },
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[1m])",
     "legendFormat": "Loafers"
    }
   ]
  },
  {
   "title": "Catd Payment In Country",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(shoehub_payments{CountryCode=\"AU\", PaymentMethod=\"Card\"}[$__rate_interval])",
     "legendFormat": "AU"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"IN\", PaymentMethod=\"Card\"}[$__rate_interval])",
     "legendFormat": "IN"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"US\", PaymentMethod=\"Card\"}[$__rate_interval])",
     "legendFormat": "US"
    }
   ]
  },
  {
   "title": "Sales Today vs Sales Last Week",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[$__interval])",
     "legendFormat": "TODAY"
    },
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[$__interval] offset 1h)",
     "legendFormat": "LAST WEEK"
    }
   ]
  },
  {
   "title": "Payment in US",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "shoehub_payments{CountryCode=\"US\"}",
     "legendFormat": "{{PaymentMethod}}"
    }
   ]
  },
  {
   "title": "Percentageof Payment Methods in the $country",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "repeat": "country",
   "targets": [
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Card\"}) / sum(shoehub_payments{CountryCode=\"$country\"}) / 100",
     "legendFormat": "Card"
    },
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Cash\"}) / sum(shoehub_payments{CountryCode=\"$country\"}) / 100",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Paypal\"}) / sum(shoehub_payments{CountryCode=\"$country\"}) / 100",
     "legendFormat": "Paypal"
    }
   ]
  }
 ]
}